# Generated by Django 2.0.7 on 2018-10-06 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(help_text='Price of product in cents')),
                ('date_start', models.DateField(default=datetime.date(1, 1, 1))),
                ('date_end', models.DateField(default=datetime.date(9999, 12, 31))),
                ('description', models.CharField(help_text='Customer facing price name', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='products.Product'),
        ),
    ]
